// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcL18UxFWrsH252cBkNDkqfoacTVaVM6Q',
    appId: '1:444582222729:web:54684d14262d124f0d5f58',
    messagingSenderId: '444582222729',
    projectId: 'ufit-d7f48',
    authDomain: 'ufit-d7f48.firebaseapp.com',
    storageBucket: 'ufit-d7f48.appspot.com',
    measurementId: 'G-HDWWW1GZ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8UwqwJkSKx4W0yAGdYvc7syCAVz8uXw',
    appId: '1:444582222729:android:f58eb28beaa9cc8f0d5f58',
    messagingSenderId: '444582222729',
    projectId: 'ufit-d7f48',
    storageBucket: 'ufit-d7f48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTv7z9DFnZBx1OIk5iNG_8wTaNHJkXYs',
    appId: '1:444582222729:ios:9646c42cf0860ea90d5f58',
    messagingSenderId: '444582222729',
    projectId: 'ufit-d7f48',
    storageBucket: 'ufit-d7f48.appspot.com',
    iosClientId: '444582222729-29rrmvpcdchm24td0rv397j9l63v4m35.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTv7z9DFnZBx1OIk5iNG_8wTaNHJkXYs',
    appId: '1:444582222729:ios:9646c42cf0860ea90d5f58',
    messagingSenderId: '444582222729',
    projectId: 'ufit-d7f48',
    storageBucket: 'ufit-d7f48.appspot.com',
    iosClientId: '444582222729-29rrmvpcdchm24td0rv397j9l63v4m35.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufit',
  );
}
